version: "3.8"

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_app
    restart: unless-stopped
    environment:
      APP_ID: ${APP_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      APP_ENV: ${APP_ENV}
